# Skill Nexis Internship - Week 1
## Assignment 2: Handling Missing Data

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Ali", "Rahul", "Sara", "John", "Aisha"],
    "Age": [20, 21, None, 22, None],
    "Marks": [85, None, 90, 78, 88]
}

df = pd.DataFrame(data)

df

    Name   Age  Marks
0    Ali  20.0   85.0
1  Rahul  21.0    NaN
2   Sara   NaN   90.0
3   John  22.0   78.0
4  Aisha   NaN   88.0

In [3]:
df.isnull().sum()

Name     0
Age      2
Marks    1
dtype: int64

In [4]:
age_mean = df["Age"].mean()
print(age_mean)

21.0

In [5]:
df["Age"] = df["Age"].fillna(age_mean)
df

    Name   Age  Marks
0    Ali  20.0   85.0
1  Rahul  21.0    NaN
2   Sara  21.0   90.0
3   John  22.0   78.0
4  Aisha  21.0   88.0

In [6]:
marks_median = df["Marks"].median()
print(marks_median)

86.5

In [7]:
df["Marks"] = df["Marks"].fillna(marks_median)
df

    Name   Age  Marks
0    Ali  20.0   85.0
1  Rahul  21.0   86.5
2   Sara  21.0   90.0
3   John  22.0   78.0
4  Aisha  21.0   88.0

In [8]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64